# Generated by Django 3.2.13 on 2022-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(default='000000', max_length=16),
        ),
    ]
