# Generated by Django 3.2.13 on 2022-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_first_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player1_moves',
            new_name='moves',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_moves',
        ),
    ]
